name: flutter_markdown
description: "A new Flutter package project."
version: 0.0.1
homepage: https:/github.com/simplecohesion/flutter_markdown

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.3.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
